export const _FOBLES_OPTIONS = {
    AI_PAGES: {
      ADD_GROUP_BUTTON: "Add group",
      COMPLETE_FIELDS_STATUS: "Complete the highlighted fields before saving.",
      GROUP_SELECTOR: "#groups .group",
      MAPPINGS_SAVED_STATUS: "Mappings saved.",
      REMOVE_GROUP_BUTTON: "Remove group",
      SAVE_MAPPINGS_BUTTON: "Save mappings",
      SECTION_TITLE: "Additional Settings",
      STATUS_SELECTOR: "#status",
      VALIDATION_ERROR_SELECTOR: "input[aria-invalid='true']",
    },
    ADMIN_PAGES: {
      ADD_BUTTON: "+ Add User Admin Page",
      COLUMN_TITLE: "Admin Pages",
      ICON_INPUT: "input[name='icon']",
      LABEL_INPUT: "input[name='label']",
      JUMP_MENU_SECTION_TITLE: "Jump Menu Buttons",
      REMOVE_BUTTON_TITLE: "Remove this Admin Page",
      ROW_SELECTOR: ".user-admin-page-row",
      SAVE_BUTTON: "Save jump flyout buttons",
      STATUS_SELECTOR: "#jump-flyout-buttons-status",
      SAVE_STATUS: "Jump flyout buttons saved.",
      URL_INPUT: "input[name='url']",
    },
    DEVELOPER: {
      DEBUG_LOGGING_SELECTOR: "#debug-logging",
      RELOAD_BUTTON_SETTING_SELECTOR: "#show-reload-extension-button",
      SAVE_BUTTON: "Save developer settings",
      STATUS_SELECTOR: "#debug-status",
      SAVE_STATUS: "Developer settings saved.",
      SECTION_TITLE: "Developer Settings",
    },
    TREE_JUMPS_COLUMN_TITLE: "Tree Jumps",
    STORAGE: {
      CLEAR_BUTTON: "Clear all stored settings",
      CLEAR_CONFIRM: "Clear all stored Fobles settings? This can't be undone.",
      CLEAR_STATUS: "All stored settings cleared.",
      CLEAR_STATUS_SELECTOR: "#clear-stored-settings-status",
      OUTPUT_SELECTOR: "#stored-settings-output",
      SECTION_TITLE: "Storage",
      VIEW_BUTTON: "View Fobles Storage",
    },
    HEADING: "Fobles Settings",
    SECTION_SELECTOR: "details.settings-section",
    SUMMARY_SELECTOR: "summary",
    SUMMARY_DIRECT_CHILD_SELECTOR: ":scope > summary",
  };