// Shared constants used by fobles generation and cleanup
export const FOBLES = {
  ATTRIBUTES: {
    BUTTON: "data-is-fobles-button",
    MARKER: "data-fobles-processed",
    STRATEGY: "data-field-strategy",
    TEMPLATE_BUTTON: "data-template-button",
    WRAPPER: "data-fobles-wrapper",
  },
  CLASSES: {
    BUTTONS: {
      ACTION: "fobles-action-button",
      ACTION_COMPACT: "fobles-action-button--compact",
      BASE: "fobles-button",
      DROP_LINK: "fobles-button--drop-link",
      FILE: "fobles-button--file",
      GENERAL_LINK: "fobles-button--general-link",
      IMAGE: "fobles-button--image",
      INTERNAL_LINK: "fobles-button--internal-link",
      MULTILIST: "fobles-button--multilist",
      MULTILIST_WITH_SEARCH: "fobles-button--multilist-with-search",
      QUICK_INFO: "fobles-button--quickinfo",
      REFERENCE_LINKS: "fobles-button--reference-links",
      TAG_LIST: "fobles-button--tag-list",
      TEMPLATE_PATH: "fobles-button--template-path",
      TREE_LIST: "fobles-button--tree-list",
      TREELIST_EX: "fobles-button--treelist-ex",
    },
    DIALOG: {
      ACTIONS: "fobles-confirm-dialog-actions",
      BASE: "fobles-confirm-dialog",
      CANCEL: "fobles-confirm-dialog-cancel",
      CONTINUE: "fobles-confirm-dialog-continue",
      SETTING: "fobles-confirm-dialog-setting",
    },
    FIELD_SPACER: "fobles-field-spacer",
    HIDDEN: "fobles-hidden",
    TOOLTIP: {
      BASE: "fobles-tooltip",
      PRIMARY: "fobles-tooltip-primary",
      SECONDARY: "fobles-tooltip-secondary",
    },
    TREE: {
      BUTTON: "tree-fobles-button",
      GLYPH_HIDDEN: "fobles-hidden",
      SPACER: "tree-fobles-spacer",
      WRAPPER: "tree-fobles-wrapper",
    },
    WRAPPERS: {
      BASE: "fobles-wrapper",
      DROP_LINK: "fobles-wrapper--drop-link",
      DROP_TREE: "fobles-wrapper--drop-tree",
      FILE: "fobles-wrapper--file",
      GENERAL_LINK: "fobles-wrapper--general-link",
      IMAGE: "fobles-wrapper--image",
      INTERNAL_LINK: "fobles-wrapper--internal-link",
      MULTILIST: "fobles-wrapper--multilist",
      MULTILIST_WITH_SEARCH: "fobles-wrapper--multilist-with-search",
      QUICK_INFO: "fobles-wrapper--quickinfo",
      REFERENCE_LINKS: "fobles-wrapper--reference-links",
      ROW: "fobles-wrapper--row",
      STACKED: "fobles-wrapper--stacked",
      TAG_LIST: "fobles-wrapper--tag-list",
      TEMPLATE_PATH: "fobles-wrapper--template-path",
      TREE_LIST: "fobles-wrapper--tree-list",
      TREELIST_EX: "fobles-wrapper--treelist-ex",
    },
  },
  CSS_PROPERTIES: {
    HEIGHT: "--fobles-height",
    LIST_HEIGHT: "--fobles-list-height",
    TREE_HEIGHT: "--tree-fobles-height",
  },
  SELECTORS: {
    BUTTON: "[data-is-fobles-button='1']",
    FRAMES: "iframe,frame",
    HIDDEN_PROCESSED: ".fobles-hidden[data-fobles-processed]",
    PROCESSED: "[data-fobles-processed]",
    TEMPLATE_BUTTON: "[data-template-button='1']",
    WRAPPER: "[data-fobles-wrapper]",
  },
  STRATEGIES: {
    DROP_LINK: "drop-link",
    DROP_TREE: "drop-tree",
    DROPLIST: "droplist",
    FILE: "file",
    GENERAL_LINK: "general-link",
    ICON: "icon",
    IMAGE: "image",
    INTERNAL_LINK: "internal-link",
    MULTILIST_OPTIONS: "multilist-options",
    MULTILIST_WITH_SEARCH: "multilist-with-search",
    QUICK_INFO_SECTION: "quick-info-section",
    REFERENCE_LINKS: "reference-links",
    TAG_LIST: "tag-list",
    TEMPLATE_PATH: "template-path",
    TREE_LIST: "tree-list",
    TREELIST_EX: "treelist-ex",
  },
  SYMBOLS: {
    TREE_BUTTON: "\u2022",
  },
  TEXT: {
    CONFIRM: {
      CANCEL: "Cancel",
      CONTINUE: "Continue",
      MESSAGE: "Sitecore will reload Content Editor with a different item query. This clears the Back and Forward navigation history for this tab.",
      SETTING: "Warn before same-tab Fobles navigation",
      TITLE: "Open this item in the current tab?",
    },
    TOOLTIP: {
      PRIMARY: "Open in this tab",
      SECONDARY: "Ctrl/Cmd+Click opens a new tab",
    },
  },
} as const;

