// Shared constants used by foble generation and cleanup
export const FOBLES = {
  ATTRIBUTES: {
    BUTTON: "data-is-foble-button",
    MARKER: "data-foble-processed",
    STRATEGY: "data-field-strategy",
    TEMPLATE_BUTTON: "data-template-button",
    WRAPPER: "data-foble-wrapper",
  },
  CSS_PROPERTIES: {
    HEIGHT: "--foble-height",
    LIST_HEIGHT: "--foble-list-height",
    TREE_HEIGHT: "--tree-foble-height",
  },
  STRATEGIES: {
    DROP_LINK: "drop-link",
    DROP_TREE: "drop-tree",
    DROPLIST: "droplist",
    FILE: "file",
    GENERAL_LINK: "general-link",
    ICON: "icon",
    IMAGE: "image",
    INTERNAL_LINK: "internal-link",
    MULTILIST_OPTIONS: "multilist-options",
    MULTILIST_WITH_SEARCH: "multilist-with-search",
    QUICK_INFO_SECTION: "quick-info-section",
    REFERENCE_LINKS: "reference-links",
    TAG_LIST: "tag-list",
    TEMPLATE_PATH: "template-path",
    TREE_LIST: "tree-list",
    TREELIST_EX: "treelist-ex",
  },
  CLASSES: {
    BUTTONS: {
      ACTION: "foble-action-button",
      ACTION_COMPACT: "foble-action-button--compact",
      BASE: "foble-button",
      DROP_LINK: "foble-button--drop-link",
      FILE: "foble-button--file",
      GENERAL_LINK: "foble-button--general-link",
      IMAGE: "foble-button--image",
      INTERNAL_LINK: "foble-button--internal-link",
      MULTILIST: "foble-button--multilist",
      MULTILIST_WITH_SEARCH: "foble-button--multilist-with-search",
      QUICK_INFO: "foble-button--quickinfo",
      REFERENCE_LINKS: "foble-button--reference-links",
      TAG_LIST: "foble-button--tag-list",
      TEMPLATE_PATH: "foble-button--template-path",
      TREE_LIST: "foble-button--tree-list",
      TREELIST_EX: "foble-button--treelist-ex",
    },
    DIALOG: {
      ACTIONS: "foble-confirm-dialog-actions",
      BASE: "foble-confirm-dialog",
      CANCEL: "foble-confirm-dialog-cancel",
      CONTINUE: "foble-confirm-dialog-continue",
      SETTING: "foble-confirm-dialog-setting",
    },
    FIELD_SPACER: "foble-field-spacer",
    HIDDEN: "foble-hidden",
    TREE: {
      BUTTON: "tree-foble-button",
      GLYPH_HIDDEN: "foble-hidden",
      SPACER: "tree-foble-spacer",
      WRAPPER: "tree-foble-wrapper",
    },
    TOOLTIP: {
      BASE: "foble-tooltip",
      PRIMARY: "foble-tooltip-primary",
      SECONDARY: "foble-tooltip-secondary",
    },
    WRAPPERS: {
      BASE: "foble-wrapper",
      DROP_LINK: "foble-wrapper--drop-link",
      FILE: "foble-wrapper--file",
      GENERAL_LINK: "foble-wrapper--general-link",
      IMAGE: "foble-wrapper--image",
      INTERNAL_LINK: "foble-wrapper--internal-link",
      MULTILIST: "foble-wrapper--multilist",
      MULTILIST_WITH_SEARCH: "foble-wrapper--multilist-with-search",
      QUICK_INFO: "foble-wrapper--quickinfo",
      REFERENCE_LINKS: "foble-wrapper--reference-links",
      ROW: "foble-wrapper--row",
      STACKED: "foble-wrapper--stacked",
      TAG_LIST: "foble-wrapper--tag-list",
      TEMPLATE_PATH: "foble-wrapper--template-path",
      TREE_LIST: "foble-wrapper--tree-list",
      TREELIST_EX: "foble-wrapper--treelist-ex",
    },
  },
  SELECTORS: {
    BUTTON: "[data-is-foble-button='1']",
    FIELD_ACTION: "a.scContentButton",
    FIELD_ACTIONS: ".scContentButtons",
    FIELD_ACTION_LINKS: ".scContentButtons > a.scContentButton",
    FIELD_CELL: "td.scEditorFieldMarkerInputCell",
    FRAMES: "iframe,frame",
    HIDDEN_PROCESSED: ".foble-hidden[data-foble-processed]",
    MULTILIST: ".scContentControlMultilist",
    MULTILIST_BOX: ".scContentControlMultilistBox",
    MULTILIST_FIELD_BUTTONS: ".scContentButtons, .scContentButton",
    MULTILIST_NAV_BUTTON: "img.scNavButton",
    PROCESSED: "[data-foble-processed]",
    TEMPLATE_BUTTON: "[data-template-button='1']",
    TREE_GLYPH: "img[id^='Tree_Glyph_']",
    TREE_ROOT: "#ContentTreeInnerPanel, #Treeview",
    TREE_NODE: ".scContentTreeNode",
    TREE_NODE_LINK: "a[id^='Tree_Node_']",
    TREE_NODES_WITH_ID: ".scContentTreeNode[id]",
    TREE_NODE_TITLE: ".scContentTreeNodeTitle",
    WRAPPER: "[data-foble-wrapper]",
  },
  SITECORE: {
    ACTION_PREFIXES: {
      FILE: "contentfile",
      GENERAL_LINK: "contentlink",
      IMAGE: "contentimage",
      INTERNAL_LINK: "contentinternallink",
      ICON: "icon",
    },
    TREE_ID_PREFIXES: {
      GLYPH: "Tree_Glyph_",
      NODE: "Tree_Node_",
      SELECT_RENDERING: "Treeview_",
    },
  },
  SYMBOLS: {
    TREE_BUTTON: "\u2022",
  },
  TEXT: {
    CONFIRM: {
      CANCEL: "Cancel",
      CONTINUE: "Continue",
      MESSAGE: "Sitecore will reload Content Editor with a different item query. This clears the Back and Forward navigation history for this tab.",
      SETTING: "Warn before same-tab Foble navigation",
      TITLE: "Open this item in the current tab?",
    },
    TOOLTIP: {
      PRIMARY: "Open in this tab",
      SECONDARY: "Ctrl/Cmd+Click opens a new tab",
    },
  },
} as const;
